# Generated by Django 3.0.6 on 2020-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200915_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='work',
            field=models.FileField(null=True, upload_to='works/'),
        ),
    ]
