# Generated by Django 3.0.6 on 2020-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200915_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='work',
        ),
        migrations.AddField(
            model_name='post',
            name='mediafile',
            field=models.FileField(null=True, upload_to='mediafile/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
