# Generated by Django 3.0.6 on 2020-09-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200916_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mediafile_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
