# Generated by Django 3.0.6 on 2020-09-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_mediafile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediafile_type',
            field=models.CharField(max_length=50),
        ),
    ]
