# Generated by Django 3.0.6 on 2020-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('imgae', 'image'), ('video', 'video')], default='', max_length=300),
        ),
    ]
