# Generated by Django 3.0.6 on 2020-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('imgae', 'image'), ('video', 'video')], max_length=300),
        ),
    ]
