# Generated by Django 3.0.6 on 2020-09-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200918_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media_type',
            new_name='mediatype',
        ),
    ]
