# Generated by Django 3.0.6 on 2020-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200918_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mediafile_type',
        ),
    ]
