# Generated by Django 3.0.6 on 2020-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_post_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediatype',
            field=models.CharField(max_length=3),
        ),
    ]
