# Generated by Django 3.0.6 on 2020-09-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200919_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mediatype',
        ),
    ]
